'''
# Concerne uniquement AKSM et en local.
TOKEN=9FnFPdG-NAAU4T0KDROPWZBkSrk7LW-ak86Dw4H5mT7KNFN0COZB_-kYWyFzc9FesdEfd_22080uC4sQC19Uwg==
HOST=http://localhost:8086
ORG=Haupt Tech
BUCKET=tiberian

CSV_FOLDER_PATH=app/storage
FLASK_ENV=development
WATCHDOG_SLEEP_INTERVAL=20

MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PASSWORD=.Logme1nn
MYSQL_DATABASE=aksm
'''